### PR TITLE
[incubator-kie-issues#822] Update DMN FEEL Handbook

### PR DESCRIPTION
**Pull request by gitgabrio**
Requires

1.    a new release of Drools, which includes this new builtin function
 2.   update test.java to the new released version

And separately, these also will need to have been merged:

https://github.com/kiegroup/dmn-feel-handbook/pull/20
https://github.com/kiegroup/dmn-feel-handbook/pull/21

Fixes https://github.com/apache/incubator-kie-issues/issues/822

@tarilabs FYI

### CODE REVIEW

**Comment by tarilabs** [comment]
To account for changes introduced with:
- https://github.com/kiegroup/dmn-feel-handbook/pull/20
- https://github.com/kiegroup/dmn-feel-handbook/pull/21

you will need to rebase.

As mentioned already, you will need _anyway_ a Drools release containing the built-in function which you introduced, in order for the testing of the FEEL results.

**Comment by gitgabrio** [comment]
Thanks @tarilabs - rebase done.

**Comment by baldimir** [comment]
Hi @tarilabs, I think this is ready to be reviewed/merged. The 1.5 spec is out an we have a PR check with latest Drools, so I think it may be fine to merge. What do you think please?

**Comment by tarilabs** [comment]
> What do you think please?

Hi @baldimir I concur as I can see the Drools SNAPSHOT is passing (the Drools latest stable I guess is not finding a "fresh" release with the commit)

Just for completeness, when you want me to merge PRs in this repo folks just lmk -- I understand discussion are happening about relocating this repo too, which will make things smoother; in the meantime feel free to ping me if I miss anything and a reminder for SEO to keep the links working: most people would expect this handbook to be reachable from https://kiegroup.github.io/dmn-feel-handbook even **_after_** repo-relocation 😉

**Pull request merged**
